CardsJS
maxdlr/because-potatoes pull request #50
Opened 2024-07-03 13:00 UTC by Gab1TN

- **Card.js**
- **add caca**

2024-07-03 13:16 UTC, redaelkarne approved these changes

2024-07-03 13:18 UTC, maxdlr requested changes

2024-07-03 13:18 UTC, maxdlr commented on public/assets/scripts/Class/Card.js
> +      "/add-card-to-stack/" + stackId,
```suggestion
      "/add-card-to-stack/",
```
C'est une requete POST, pas d'argument dans la route.

2024-07-03 13:18 UTC, maxdlr commented on public/assets/scripts/Class/Card.js
> +    return Card.fromData(response);
```suggestion
    return response.card;
```

2024-07-03 13:18 UTC, maxdlr commented on public/assets/scripts/Class/Card.js
> +    return response.map((data) => Card.fromData(data));
```suggestion
    return response.cards;
```

2024-07-04 05:31 UTC, maxdlr requested changes

2024-07-04 12:51 UTC, maxdlr requested changes

2024-07-04 13:06 UTC, maxdlr approved these changes

2024-07-04 13:06 UTC, merged